In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.cross_decomposition import PLSRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
# Cargar tu conjunto de datos
data = pd.read_csv("/content/drive/My Drive/Tesis/Dataset/nuevo_dataset_prueba.csv")


Mounted at /content/drive


In [ ]:
# Crear el DataFrame Referencia
y = data['Humedad']
#y=data['CSS BRIX°']
X =data[['NIR_R', 'NIR_S', 'NIR_T', 'NIR_U', 'NIR_V', 'NIR_W', 'Vis_Violet', 'Vis_Blue', 'Vis_Green', 'Vis_Yellow', 'Vis_Orange', 'Vis_Red']]

In [ ]:
# Dividir los datos en conjunto de entrenamiento y conjunto de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=42)

In [ ]:
# Definir y entrenar modelo PLS
pls_model = PLSRegression(n_components=5)  # Elige el número de componentes PLS que deseas
pls_model.fit(X_train, y_train)


PLSRegression(n_components=5)

In [ ]:
# Evaluar rendimiento del modelo PLS en conjunto de prueba
y_pred_pls = pls_model.predict(X_test)
mse_pls = mean_squared_error(y_test, y_pred_pls)
r2_pls = r2_score(y_test, y_pred_pls)

print("Rendimiento del modelo de PLS:")
print("MSE:", mse_pls)
print("R-cuadrado:", r2_pls)
print()

print(y_pred_pls)
print(X_test[1:2])



Rendimiento del modelo de PLS:
MSE: 2.706242028457155
R-cuadrado: -0.4809396548960425

[[50.97050965]
 [50.34521895]
 [49.96660263]
 [47.26359017]
 [50.25122731]]
       NIR_R    NIR_S    NIR_T   NIR_U    NIR_V   NIR_W  Vis_Violet  Vis_Blue  \
53  2247.625  486.668  150.879  83.128  136.228  68.788     375.522   271.928   

    Vis_Green  Vis_Yellow  Vis_Orange  Vis_Red  
53    868.575    1445.979    1893.665   1396.2  


In [ ]:
# Calcula las medias manualmente
X_mean = np.mean(X_train, axis=0)
y_mean = np.mean(y_train, axis=0)

# Extrae los coeficientes
coefficients = pls_model.coef_
print("Coefficients:", coefficients)
print("X mean:", X_mean)
print("y mean:", y_mean)


Coefficients: [[-1.77840272]
 [-2.8716605 ]
 [-0.84114434]
 [ 2.96863434]
 [ 1.04063975]
 [ 1.15475075]
 [-0.7981967 ]
 [ 3.09597443]
 [-0.75304486]
 [ 2.51222512]
 [-0.61164474]
 [-2.54553941]]
X mean: NIR_R         2912.587789
NIR_S          812.686811
NIR_T          229.912558
NIR_U          129.759305
NIR_V          194.642863
NIR_W          111.509379
Vis_Violet     531.383253
Vis_Blue       468.395305
Vis_Green     1369.171021
Vis_Yellow    1752.066611
Vis_Orange    1997.704895
Vis_Red       1438.878874
dtype: float64
y mean: 52.830448471142525


/usr/local/lib/python3.10/dist-packages/sklearn/cross_decomposition/_pls.py:503: FutureWarning: The attribute `coef_` will be transposed in version 1.3 to be consistent with other linear models in scikit-learn. Currently, `coef_` has a shape of (n_features, n_targets) and in the future it will have a shape of (n_targets, n_features).
  warnings.warn(


In [ ]:
# prompt: colocar en una linea los coeficientes

coefs_string = ', '.join(map(str, coefficients.flatten()))
print("Coeficientes (una línea):")
print(coefs_string)

# Convertir el Pandas Series a una lista antes de unir
MediaX_string = ', '.join(map(str, X_mean.tolist()))  # Cambio aquí
print("Media X (una línea):")  # Etiqueta cambiada para mayor claridad
print(MediaX_string)


Coeficientes (una línea):
-1.7784027227679085, -2.8716605005514624, -0.8411443448452596, 2.9686343447350625, 1.0406397502842235, 1.1547507457353579, -0.7981967008702849, 3.0959744317636204, -0.7530448645440819, 2.512225118758314, -0.6116447363470329, -2.54553941317361
Media X (una línea):
2912.5877894736836, 812.6868105263159, 229.91255789473684, 129.75930526315793, 194.64286315789474, 111.50937894736842, 531.3832526315789, 468.39530526315787, 1369.1710210526314, 1752.0666105263156, 1997.7048947368423, 1438.8788736842107


In [ ]:
# Crear el DataFrame Referencia
y=data['°BRIX']
X =data[['NIR_R', 'NIR_S', 'NIR_T', 'NIR_U', 'NIR_V', 'NIR_W', 'Vis_Violet', 'Vis_Blue', 'Vis_Green', 'Vis_Yellow', 'Vis_Orange', 'Vis_Red']]

# Dividir los datos en conjunto de entrenamiento y conjunto de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=42)

# Definir y entrenar modelo PLS
pls_model = PLSRegression(n_components=5)  # Elige el número de componentes PLS que deseas
pls_model.fit(X_train, y_train)

# Evaluar rendimiento del modelo PLS en conjunto de prueba
y_pred_pls = pls_model.predict(X_test)
mse_pls = mean_squared_error(y_test, y_pred_pls)
r2_pls = r2_score(y_test, y_pred_pls)
print(y_pred_pls[1])
print("Rendimiento del modelo de PLS:")
print("MSE:", mse_pls)
print("R-cuadrado:", r2_pls)

# Calcula las medias manualmente
X_mean = np.mean(X_train, axis=0)
y_mean = np.mean(y_train, axis=0)

# Extrae los coeficientes
coefficients = pls_model.coef_
print("Coefficients:", coefficients)
print("X mean:", X_mean)
print("y mean:", y_mean)

# prompt: colocar en una linea los coeficientes
coefs_string = ', '.join(map(str, coefficients.flatten()))
print("Coeficientes (una línea):")
print(coefs_string)

# Convertir el Pandas Series a una lista antes de unir
MediaX_string = ', '.join(map(str, X_mean.tolist()))  # Cambio aquí
print("Media X (una línea):")  # Etiqueta cambiada para mayor claridad
print(MediaX_string)

[8.57925727]
Rendimiento del modelo de PLS:
MSE: 0.4431547207857058
R-cuadrado: -0.045779625437171845
Coefficients: [[ 0.2502639 ]
 [ 0.56447716]
 [ 0.3313363 ]
 [-0.38726113]
 [-0.33065386]
 [-0.2768326 ]
 [ 0.19947446]
 [-0.29932602]
 [ 0.04791949]
 [-0.7088145 ]
 [ 0.06498176]
 [ 0.42143522]]
X mean: NIR_R         2912.587789
NIR_S          812.686811
NIR_T          229.912558
NIR_U          129.759305
NIR_V          194.642863
NIR_W          111.509379
Vis_Violet     531.383253
Vis_Blue       468.395305
Vis_Green     1369.171021
Vis_Yellow    1752.066611
Vis_Orange    1997.704895
Vis_Red       1438.878874
dtype: float64
y mean: 8.454449903436528
Coeficientes (una línea):
0.2502638987075172, 0.564477158236186, 0.3313363034231872, -0.3872611279448679, -0.330653858187407, -0.27683260058398756, 0.19947445966178018, -0.2993260158617951, 0.04791948886042247, -0.7088145034395203, 0.06498176348379837, 0.4214352235724421
Media X (una línea):
2912.5877894736836, 812.6868105263159, 229.912557

/usr/local/lib/python3.10/dist-packages/sklearn/cross_decomposition/_pls.py:503: FutureWarning: The attribute `coef_` will be transposed in version 1.3 to be consistent with other linear models in scikit-learn. Currently, `coef_` has a shape of (n_features, n_targets) and in the future it will have a shape of (n_targets, n_features).
  warnings.warn(


In [ ]:
# prompt: Realizar lo anterior pero con variables para pH

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.cross_decomposition import PLSRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from google.colab import drive
drive.mount('/content/drive')
# Cargar tu conjunto de datos
data = pd.read_csv("/content/drive/My Drive/Tesis/Dataset/nuevo_dataset_prueba.csv")

# Crear el DataFrame Referencia
y = data['pH']
X =data[['NIR_R', 'NIR_S', 'NIR_T', 'NIR_U', 'NIR_V', 'NIR_W', 'Vis_Violet', 'Vis_Blue', 'Vis_Green', 'Vis_Yellow', 'Vis_Orange', 'Vis_Red']]
# Dividir los datos en conjunto de entrenamiento y conjunto de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=42)
# Definir y entrenar modelo PLS
pls_model = PLSRegression(n_components=5)  # Elige el número de componentes PLS que deseas
pls_model.fit(X_train, y_train)

# Evaluar rendimiento del modelo PLS en conjunto de prueba
y_pred_pls = pls_model.predict(X_test)
mse_pls = mean_squared_error(y_test, y_pred_pls)
r2_pls = r2_score(y_test, y_pred_pls)

print("Rendimiento del modelo de PLS:")
print("MSE:", mse_pls)
print("R-cuadrado:", r2_pls)
print()

print(y_pred_pls)
print(X_test[1:2])


# Calcula las medias manualmente
X_mean = np.mean(X_train, axis=0)
y_mean = np.mean(y_train, axis=0)

# Extrae los coeficientes
coefficients = pls_model.coef_
print("Coefficients:", coefficients)
print("X mean:", X_mean)
print("y mean:", y_mean)


coefs_string = ', '.join(map(str, coefficients.flatten()))
print("Coeficientes (una línea):")
print(coefs_string)

# Convertir el Pandas Series a una lista antes de unir
MediaX_string = ', '.join(map(str, X_mean.tolist()))  # Cambio aquí
print("Media X (una línea):")  # Etiqueta cambiada para mayor claridad
print(MediaX_string)


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Rendimiento del modelo de PLS:
MSE: 0.01747090824301045
R-cuadrado: -1.0119895169839799

[[6.54592663]
 [6.58514209]
 [6.61169177]
 [6.67648609]
 [6.58704862]]
       NIR_R    NIR_S    NIR_T   NIR_U    NIR_V   NIR_W  Vis_Violet  Vis_Blue  \
53  2247.625  486.668  150.879  83.128  136.228  68.788     375.522   271.928   

    Vis_Green  Vis_Yellow  Vis_Orange  Vis_Red  
53    868.575    1445.979    1893.665   1396.2  
Coefficients: [[ 0.07124406]
 [ 0.06992267]
 [ 0.02606607]
 [-0.07197948]
 [-0.02252665]
 [-0.02617296]
 [-0.01552518]
 [-0.09565914]
 [-0.00017907]
 [-0.09009312]
 [ 0.0414934 ]
 [ 0.10515641]]
X mean: NIR_R         2912.587789
NIR_S          812.686811
NIR_T          229.912558
NIR_U          129.759305
NIR_V          194.642863
NIR_W          111.509379
Vis_Violet     531.383253
Vis_Blue       468.395305
Vis_Green     1369.171021
Vis_Yellow   

/usr/local/lib/python3.10/dist-packages/sklearn/cross_decomposition/_pls.py:503: FutureWarning: The attribute `coef_` will be transposed in version 1.3 to be consistent with other linear models in scikit-learn. Currently, `coef_` has a shape of (n_features, n_targets) and in the future it will have a shape of (n_targets, n_features).
  warnings.warn(


In [ ]:
# prompt: Realizar lo anterior pero con variables para IM

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.cross_decomposition import PLSRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from google.colab import drive
drive.mount('/content/drive')
# Cargar tu conjunto de datos
data = pd.read_csv("/content/drive/My Drive/Tesis/Dataset/nuevo_dataset_prueba.csv")

# Crear el DataFrame Referencia
y = data['IM']
X =data[['NIR_R', 'NIR_S', 'NIR_T', 'NIR_U', 'NIR_V', 'NIR_W', 'Vis_Violet', 'Vis_Blue', 'Vis_Green', 'Vis_Yellow', 'Vis_Orange', 'Vis_Red']]
# Dividir los datos en conjunto de entrenamiento y conjunto de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=42)
# Definir y entrenar modelo PLS
pls_model = PLSRegression(n_components=5)  # Elige el número de componentes PLS que deseas
pls_model.fit(X_train, y_train)

# Evaluar rendimiento del modelo PLS en conjunto de prueba
y_pred_pls = pls_model.predict(X_test)
mse_pls = mean_squared_error(y_test, y_pred_pls)
r2_pls = r2_score(y_test, y_pred_pls)

print("Rendimiento del modelo de PLS:")
print("MSE:", mse_pls)
print("R-cuadrado:", r2_pls)
print()

print(y_pred_pls)
print(X_test[1:2])


# Calcula las medias manualmente
X_mean = np.mean(X_train, axis=0)
y_mean = np.mean(y_train, axis=0)

# Extrae los coeficientes
coefficients = pls_model.coef_
print("Coefficients:", coefficients)
print("X mean:", X_mean)
print("y mean:", y_mean)


coefs_string = ', '.join(map(str, coefficients.flatten()))
print("Coeficientes (una línea):")
print(coefs_string)

# Convertir el Pandas Series a una lista antes de unir
MediaX_string = ', '.join(map(str, X_mean.tolist()))  # Cambio aquí
print("Media X (una línea):")  # Etiqueta cambiada para mayor claridad
print(MediaX_string)


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Rendimiento del modelo de PLS:
MSE: 13.415029303157556
R-cuadrado: -0.017132590832514394

[[51.97338667]
 [42.27497308]
 [48.19952485]
 [50.42081731]
 [42.69376341]]
       NIR_R    NIR_S    NIR_T   NIR_U    NIR_V   NIR_W  Vis_Violet  Vis_Blue  \
53  2247.625  486.668  150.879  83.128  136.228  68.788     375.522   271.928   

    Vis_Green  Vis_Yellow  Vis_Orange  Vis_Red  
53    868.575    1445.979    1893.665   1396.2  
Coefficients: [[ 1.39789356]
 [ 7.59593294]
 [ 4.09952508]
 [-4.07057915]
 [-4.51823149]
 [-3.61966536]
 [ 3.63072991]
 [ 0.5050465 ]
 [ 1.41782754]
 [-7.47128068]
 [-1.89095745]
 [ 2.38536047]]
X mean: NIR_R         2912.587789
NIR_S          812.686811
NIR_T          229.912558
NIR_U          129.759305
NIR_V          194.642863
NIR_W          111.509379
Vis_Violet     531.383253
Vis_Blue       468.395305
Vis_Green     1369.171021
Vis_Yel

/usr/local/lib/python3.10/dist-packages/sklearn/cross_decomposition/_pls.py:503: FutureWarning: The attribute `coef_` will be transposed in version 1.3 to be consistent with other linear models in scikit-learn. Currently, `coef_` has a shape of (n_features, n_targets) and in the future it will have a shape of (n_targets, n_features).
  warnings.warn(
